### ISSUE TITLE
Why namedtuple is parsed as tuple?

### ISSUE THREAD

**Issue by NoAnyLove** [irmen/Serpent#26]
collections.namedtuple and tuple are quite different, I'm quite confused that why the serilized namedtuple becomes tuple?

```
>>> import serpent
>>> import collections
>>> Point=collections.namedtuple('Point', list('xyz'))
>>> pt=Point(1,2,3)
>>> serpent.dumps(pt)
'# serpent utf-8 python2.6\n(1,2,3)'
>>> serpent.loads(_)
(1, 2, 3)
```

**Comment by irmen** [comment]
Serpent creates literal expressions (that are to be parsed by eval, or ast.literal_eval rather).  Python has no literal expression to create a namedtuple, so all we can do is create a tuple out of it. Namedtuple inherits from tuple, by the way.

If serpent chose to serialize it into a dictionary (thereby preserving the keys as well as their values) we lose the order.  It's a loss either way.

**Comment by NoAnyLove** [comment]
Hi irmen,

I'm not familiar ast.literal_eval, but I think it is possible to create a namedtuple with an literal expression, for example,

```
>>> import collections
>>> stmt="collections.namedtuple('Point', list('xyz'))(1,2,3)"
>>> eval(stmt)
Point(x=1, y=2, z=3)
```

I'm not sure if this is correct or not.

**Comment by irmen** [comment]
``ast.literal_eval`` is the "safe" variant from ``eval``.  See https://docs.python.org/3/library/ast.html#ast.literal_eval

``eval`` executes aritrary Python code, which is highly undesirable when dealing with serialization formats (because the data may come from anywhere, and you don't want to run arbitrary code).
``ast.literal_eval`` on the other hand only evaluates *literal expressions* which are defined as being a Python literal (such as a string, a number, or a boolean) or a built-in container type (set, dict, list, tuple).

The end result of the expression you're evaluating in your comment is a data structure, however the expression describing it is a piece of code instead of a literal expression. The piece of code cointains:
- an attribute lookup of "namedtuple" in the "collections" module;
- a function call creating a list with elements x,y,z
- a function call creating a namedtuple type
- a function call creating a namedtuple instance containing the values 1,2,3
