### ISSUE TITLE
Pandas is supported?

### ISSUE THREAD

**Issue by wyujie** [irmen/Serpent#41]
Hi, @irmen 

Are the data structures defined in pandas like dataframe or series supported? If not, how to make a customized structure to be supported?

Thanks.

**Comment by irmen** [comment]
remark: I don't advise trying to serialize huge pandas data which is stored in a highly efficient binary format, into a verbose text format. So be warned about potentially enormous memory use or otherwise...

That said. Serpent supports the types listed in the readme.  You can add support for your own types by registering a custom serializer using register_class() / registerClass() / RegisterClass()

**Comment by wyujie** [comment]
Thank you !
